import postgres from 'postgres';
import 'dotenv/config';

const sql = postgres({
	host: process.env.POSTGRES_URL,
	port: 5432,
	database: process.env.DB_NAME,
	username: process.env.DB_USERNAME,
	password: process.env.DB_PASSWORD,
});

await sql`
CREATE TABLE students (
		id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
		"name" varchar NOT NULL,
		email varchar NOT NULL,
		"password" varchar NOT NULL,
		CONSTRAINT email_unique UNIQUE (email),
		CONSTRAINT students_pk PRIMARY KEY (id)
);`;

await sql`
CREATE TABLE attendances (
			id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
			studentid int4 NOT NULL,
			coursecode varchar NOT NULL,
			entradafecha varchar NOT NULL,
			salidafecha varchar NULL,
			entradaubicacion varchar NOT NULL,
			salidaubicacion varchar NULL,
			entradaip varchar NOT NULL,
			salidaip varchar NULL,
			entradamac varchar NOT NULL,
			salidamac varchar NULL,
			totalhoras float4 NULL,
			CONSTRAINT attendance_pk PRIMARY KEY (id),
			CONSTRAINT attendance_students_fk FOREIGN KEY (studentid) REFERENCES public.students(id)
);`;

process.exit();
